nelmio_api_doc:
    documentation:
        info:
            title: Feature Flags API
            version: 1.0.0
        paths:
            /login:
                post:
                    summary: Get JWT token
                    tags:
                        - Auth
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                            example: admin@example.com
                                        password:
                                            type: string
                                            example: password
                    responses:
                        '200':
                            description: JWT token
                        '401':
                            description: Invalid credentials
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []
    areas:
        path_patterns:
            - ^/feature
            - ^/login
